"""empty message

Revision ID: 22f6f07fc3e7
Revises: 61fb62f47d4f
Create Date: 2020-04-25 14:02:51.228243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f6f07fc3e7'
down_revision = '61fb62f47d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts_instruments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_instruments',
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name='contacts_instruments_contact_id_fkey'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name='contacts_instruments_instrument_id_fkey'),
    sa.PrimaryKeyConstraint('contact_id', 'instrument_id', name='contacts_instruments_pkey')
    )
    # ### end Alembic commands ###
