DEBUG = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
RECORDS_PER_PAGE = 20
AUTH0_DOMAIN = 'dev-udacity.auth0.com'
ALGORITHMS = ['RS256']
API_AUDIENCE = 'error-logging-app'
CLIENT_ID = 'r2f4Pw7sQnbZpsISjWweexbze0pbaK7r'
REDIRECT_URI = 'http://127.0.0.1:5000/'
DATE_FORMAT = '%Y-%m-%d %H:%M:%S'